// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC4xyrgsGktRyMUf94yG49yfG3Ba5XyYk',
    appId: '1:249215294825:web:e1f7bc517f1acaa99071f8',
    messagingSenderId: '249215294825',
    projectId: 'gabbers-app-1',
    authDomain: 'gabbers-app-1.firebaseapp.com',
    storageBucket: 'gabbers-app-1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn7JszxZgw68aZFmzmfGVV0wjP5HXL6Iw',
    appId: '1:249215294825:android:92550af161d2b4c19071f8',
    messagingSenderId: '249215294825',
    projectId: 'gabbers-app-1',
    storageBucket: 'gabbers-app-1.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDC4xyrgsGktRyMUf94yG49yfG3Ba5XyYk',
    appId: '1:249215294825:web:83341ffb5ac8baf19071f8',
    messagingSenderId: '249215294825',
    projectId: 'gabbers-app-1',
    authDomain: 'gabbers-app-1.firebaseapp.com',
    storageBucket: 'gabbers-app-1.appspot.com',
  );

}